[target.'cfg(all())']
rustflags = [
    "-Wclippy::all",
    "-Wclippy::alloc_instead_of_core",
    "-Wclippy::arithmetic_side_effects",
    "-Wclippy::as_underscore",
    "-Wclippy::assertions_on_result_states",
    "-Wclippy::cargo",
    "-Wclippy::clone_on_ref_ptr",
    "-Wclippy::dbg_macro",
    "-Wclippy::decimal_literal_representation",
    "-Wclippy::default_numeric_fallback",
    "-Wclippy::deref_by_slicing",
    "-Wclippy::else_if_without_else",
    "-Wclippy::exhaustive_enums",
    "-Wclippy::exhaustive_structs",
    "-Wclippy::exit",
    "-Wclippy::expect_used",
    "-Wclippy::float_arithmetic",
    "-Wclippy::float_cmp_const",
    "-Wclippy::fn_to_numeric_cast_any",
    "-Wclippy::format_push_string",
    "-Wclippy::get_unwrap",
    "-Wclippy::if_then_some_else_none",
    "-Wclippy::indexing_slicing",
    "-Wclippy::integer_division",
    "-Wclippy::let_underscore_must_use",
    "-Wclippy::lossy_float_literal",
    "-Wclippy::map_err_ignore",
#    "-Wclippy::missing_docs_in_private_items",
    "-Wclippy::mixed_read_write_in_expression",
    "-Wclippy::multiple_inherent_impl",
    "-Wclippy::non_ascii_literal",
    "-Wclippy::panic",
    "-Wclippy::panic_in_result_fn",
    "-Wclippy::partial_pub_fields",
    "-Wclippy::pedantic",
    "-Wclippy::print_stderr",
    "-Wclippy::print_stdout",
    "-Wclippy::rc_buffer",
    "-Wclippy::rc_mutex",
    "-Wclippy::rest_pat_in_fully_bound_structs",
    "-Wclippy::same_name_method",
    "-Wclippy::self_named_module_files",
    "-Wclippy::semicolon_inside_block",
    "-Wclippy::separated_literal_suffix",
    "-Wclippy::shadow_same",
    "-Wclippy::shadow_unrelated",
    "-Wclippy::string_slice",
    "-Wclippy::string_to_string",
    "-Wclippy::suspicious_xor_used_as_pow",
    "-Wclippy::todo",
    "-Wclippy::try_err",
    "-Wclippy::undocumented_unsafe_blocks",
    "-Wclippy::unimplemented",
    "-Wclippy::unnecessary_safety_comment",
    "-Wclippy::unnecessary_safety_doc",
    "-Wclippy::unneeded_field_pattern",
    "-Wclippy::unreachable",
    "-Wclippy::unwrap_used",
    "-Wclippy::use_debug",
    "-Wclippy::wildcard_enum_match_arm",
    "-Welided_lifetimes_in_paths",
    "-Wexplicit_outlives_requirements",
    "-Wfuture_incompatible",
    "-Wkeyword_idents",
    "-Wlet_underscore",
    "-Wmissing_debug_implementations",
#    "-Wmissing_docs",
    "-Wnon_ascii_idents",
    "-Wnoop_method_call",
    "-Wsingle_use_lifetimes",
    "-Wtrivial_casts",
    "-Wtrivial_numeric_casts",
    "-Wunreachable_pub",
    "-Wunsafe_code",
    "-Wunsafe_op_in_unsafe_fn",
    "-Wunused",
    "-Wunused_crate_dependencies",
    "-Wunused_import_braces",
    "-Wunused_lifetimes",
    "-Wunused_macro_rules",
    "-Wunused_qualifications",
    "-Wdead_code",
    "-Aclippy::default_trait_access",
	# Temporary until I wrote more docs
	"-Aclippy::missing_errors_doc",
]
